{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mdemg.secretName" . }}
  labels:
    {{- include "mdemg.labels" . | nindent 4 }}
type: Opaque
stringData:
  neo4j-uri: {{ .Values.secrets.neo4jUri | quote }}
  neo4j-user: {{ .Values.secrets.neo4jUser | quote }}
  neo4j-pass: {{ .Values.secrets.neo4jPass | quote }}
  openai-api-key: {{ .Values.secrets.openaiApiKey | quote }}
  api-keys: {{ .Values.secrets.apiKeys | quote }}
{{- end }}
