package jiminy

import (
	"encoding/json"
	"fmt"
	"testing"
	"time"

	"mdemg/internal/config"
)

func TestTicketManager_IssueAndValidate(t *testing.T) {
	tm := NewTicketManager("test-secret-key-32bytes!!", 4, 0)

	payload := TicketPayload{
		SpaceID:   "test-space",
		SessionID: "test-session",
		LastSeq:   42,
		TrustScore: 0.75,
		EscalationSnapshot: map[string]EscalationEntry{
			"node-1": {NodeID: "node-1", Level: EscalationWarned, IgnoreCount: 2},
			"node-2": {NodeID: "node-2", Level: EscalationEscalated, IgnoreCount: 4},
		},
		ActiveConstraintIDs: []string{"node-1", "node-2"},
		ConversationPhase:   "active",
	}

	ticket, err := tm.IssueTicket(payload)
	if err != nil {
		t.Fatalf("IssueTicket failed: %v", err)
	}
	if ticket == nil {
		t.Fatal("ticket is nil")
	}
	if ticket.Signature == "" {
		t.Fatal("ticket signature is empty")
	}

	// Validate round-trip
	restored, err := tm.ValidateTicket(ticket)
	if err != nil {
		t.Fatalf("ValidateTicket failed: %v", err)
	}
	if restored.Version != J17Version {
		t.Errorf("version = %q, want %q", restored.Version, J17Version)
	}
	if restored.SpaceID != "test-space" {
		t.Errorf("space_id = %q, want %q", restored.SpaceID, "test-space")
	}
	if restored.SessionID != "test-session" {
		t.Errorf("session_id = %q, want %q", restored.SessionID, "test-session")
	}
	if restored.LastSeq != 42 {
		t.Errorf("last_seq = %d, want 42", restored.LastSeq)
	}
	if restored.TrustScore != 0.75 {
		t.Errorf("trust_score = %f, want 0.75", restored.TrustScore)
	}
	if len(restored.EscalationSnapshot) != 2 {
		t.Errorf("escalation_snapshot len = %d, want 2", len(restored.EscalationSnapshot))
	}
	if restored.EscalationSnapshot["node-1"].Level != EscalationWarned {
		t.Errorf("node-1 level = %q, want %q", restored.EscalationSnapshot["node-1"].Level, EscalationWarned)
	}
}

func TestTicketManager_TamperDetection(t *testing.T) {
	tm := NewTicketManager("test-secret-key-32bytes!!", 4, 0)

	payload := TicketPayload{
		SpaceID:   "test-space",
		SessionID: "test-session",
		LastSeq:   10,
	}

	ticket, err := tm.IssueTicket(payload)
	if err != nil {
		t.Fatalf("IssueTicket failed: %v", err)
	}

	// Tamper with payload
	var p TicketPayload
	_ = json.Unmarshal(ticket.Payload, &p)
	p.TrustScore = 1.0 // try to boost trust
	tampered, _ := json.Marshal(p)
	ticket.Payload = tampered

	_, err = tm.ValidateTicket(ticket)
	if err == nil {
		t.Fatal("expected validation to fail for tampered ticket")
	}
}

func TestTicketManager_TTLExpiry(t *testing.T) {
	tm := NewTicketManager("test-secret", 1, 0) // 1 hour TTL

	payload := TicketPayload{
		SpaceID:   "test-space",
		SessionID: "test-session",
	}

	ticket, err := tm.IssueTicket(payload)
	if err != nil {
		t.Fatalf("IssueTicket failed: %v", err)
	}

	// Manually expire the ticket by modifying the payload's IssuedAt
	var p TicketPayload
	_ = json.Unmarshal(ticket.Payload, &p)
	p.IssuedAt = time.Now().Add(-2 * time.Hour) // 2 hours ago
	expired, _ := json.Marshal(p)

	// Re-sign with the correct key to isolate TTL check from tamper check
	ticket.Payload = expired
	ticket.Signature = tm.sign(expired)

	_, err = tm.ValidateTicket(ticket)
	if err == nil {
		t.Fatal("expected validation to fail for expired ticket")
	}
}

func TestTicketManager_DifferentSecretFails(t *testing.T) {
	tm1 := NewTicketManager("secret-one", 4, 0)
	tm2 := NewTicketManager("secret-two", 4, 0)

	payload := TicketPayload{
		SpaceID:   "test-space",
		SessionID: "test-session",
	}

	ticket, err := tm1.IssueTicket(payload)
	if err != nil {
		t.Fatalf("IssueTicket failed: %v", err)
	}

	// Validate with different secret should fail
	_, err = tm2.ValidateTicket(ticket)
	if err == nil {
		t.Fatal("expected validation to fail with different secret")
	}
}

func TestTicketManager_AutoGeneratedSecret(t *testing.T) {
	tm := NewTicketManager("", 4, 0) // empty secret → auto-generate

	payload := TicketPayload{
		SpaceID:   "test-space",
		SessionID: "test-session",
	}

	ticket, err := tm.IssueTicket(payload)
	if err != nil {
		t.Fatalf("IssueTicket failed: %v", err)
	}

	// Should still round-trip with same manager
	_, err = tm.ValidateTicket(ticket)
	if err != nil {
		t.Fatalf("ValidateTicket with auto-generated secret failed: %v", err)
	}
}

func TestTicketManager_RestoreEscalation(t *testing.T) {
	tm := NewTicketManager("test-secret", 4, 0)

	// Create escalation tracker and populate state
	cfg := defaultTestConfig()
	tracker := NewEscalationTracker(cfg)

	// Simulate some escalation state
	tracker.RecordSurface("sess-1", "node-1")
	tracker.RecordOutcome("sess-1", "node-1", OutcomeIgnored) // ignore 1
	tracker.RecordOutcome("sess-1", "node-1", OutcomeIgnored) // ignore 2 → warned

	level := tracker.GetState("sess-1", "node-1")
	if level != EscalationWarned {
		t.Fatalf("pre-ticket level = %q, want %q", level, EscalationWarned)
	}

	// Export state and create ticket
	states := tracker.ExportState("sess-1")
	payload := TicketPayload{
		SpaceID:            "test-space",
		SessionID:          "sess-1",
		LastSeq:            10,
		EscalationSnapshot: states,
	}

	ticket, err := tm.IssueTicket(payload)
	if err != nil {
		t.Fatalf("IssueTicket failed: %v", err)
	}

	// Create fresh tracker (simulating context reset)
	newTracker := NewEscalationTracker(cfg)
	freshLevel := newTracker.GetState("sess-1", "node-1")
	if freshLevel != EscalationInactive {
		t.Fatalf("fresh tracker should have inactive, got %q", freshLevel)
	}

	// Restore from ticket
	_, err = tm.RestoreFromTicket(ticket, newTracker)
	if err != nil {
		t.Fatalf("RestoreFromTicket failed: %v", err)
	}

	// Verify escalation state was restored
	restoredLevel := newTracker.GetState("sess-1", "node-1")
	if restoredLevel != EscalationWarned {
		t.Errorf("restored level = %q, want %q", restoredLevel, EscalationWarned)
	}
}

func TestTicketManager_GetLastTicket(t *testing.T) {
	tm := NewTicketManager("test-secret", 4, 0)

	// No ticket yet
	if tk := tm.GetLastTicket("sess-1"); tk != nil {
		t.Fatal("expected nil for non-existent session")
	}

	payload := TicketPayload{
		SpaceID:   "test-space",
		SessionID: "sess-1",
		LastSeq:   5,
	}

	_, err := tm.IssueTicket(payload)
	if err != nil {
		t.Fatalf("IssueTicket failed: %v", err)
	}

	tk := tm.GetLastTicket("sess-1")
	if tk == nil {
		t.Fatal("expected non-nil ticket after issue")
	}
}

func TestTicketManager_LRUEviction(t *testing.T) {
	tm := NewTicketManager("test-secret", 4, 3) // maxSize = 3

	// Issue tickets for 5 different sessions
	for i := 1; i <= 5; i++ {
		_, err := tm.IssueTicket(TicketPayload{
			SpaceID:   "test-space",
			SessionID: fmt.Sprintf("sess-%d", i),
			LastSeq:   int64(i),
		})
		if err != nil {
			t.Fatalf("IssueTicket sess-%d failed: %v", i, err)
		}
	}

	// Only 3 tickets should remain (sess-3, sess-4, sess-5)
	tm.mu.RLock()
	mapLen := len(tm.lastTickets)
	listLen := tm.lruList.Len()
	tm.mu.RUnlock()

	if mapLen != 3 {
		t.Errorf("lastTickets map size = %d, want 3", mapLen)
	}
	if listLen != 3 {
		t.Errorf("lruList length = %d, want 3", listLen)
	}

	// Oldest sessions (sess-1, sess-2) should be evicted
	if tk := tm.GetLastTicket("sess-1"); tk != nil {
		t.Error("sess-1 should have been evicted")
	}
	if tk := tm.GetLastTicket("sess-2"); tk != nil {
		t.Error("sess-2 should have been evicted")
	}

	// Newest sessions should still be present
	for i := 3; i <= 5; i++ {
		if tk := tm.GetLastTicket(fmt.Sprintf("sess-%d", i)); tk == nil {
			t.Errorf("sess-%d should still be present", i)
		}
	}

	// Re-issuing for existing session should not grow the map
	_, err := tm.IssueTicket(TicketPayload{
		SpaceID:   "test-space",
		SessionID: "sess-3",
		LastSeq:   99,
	})
	if err != nil {
		t.Fatalf("re-issue sess-3 failed: %v", err)
	}

	tm.mu.RLock()
	finalLen := len(tm.lastTickets)
	tm.mu.RUnlock()

	if finalLen != 3 {
		t.Errorf("after re-issue, map size = %d, want 3", finalLen)
	}
}

func TestSequenceTracker_BasicOperations(t *testing.T) {
	st := NewSequenceTracker(100)

	if st.Current() != 0 {
		t.Errorf("initial counter = %d, want 0", st.Current())
	}

	seq1 := st.Next()
	if seq1 != 1 {
		t.Errorf("first Next() = %d, want 1", seq1)
	}

	seq2 := st.Next()
	if seq2 != 2 {
		t.Errorf("second Next() = %d, want 2", seq2)
	}

	if st.Current() != 2 {
		t.Errorf("current after 2 Next() = %d, want 2", st.Current())
	}
}

func TestSequenceTracker_RecordAndReplay(t *testing.T) {
	st := NewSequenceTracker(100)

	// Record 5 events
	for i := 0; i < 5; i++ {
		st.RecordGuidance("space-1", "sess-1", i+1, "")
	}

	if st.Count() != 5 {
		t.Errorf("count = %d, want 5", st.Count())
	}

	// Replay all events since seq 0
	events := st.EventsSince(0, 50)
	if len(events) != 5 {
		t.Fatalf("EventsSince(0) = %d events, want 5", len(events))
	}
	if events[0].Seq != 1 {
		t.Errorf("first event seq = %d, want 1", events[0].Seq)
	}
	if events[4].Seq != 5 {
		t.Errorf("last event seq = %d, want 5", events[4].Seq)
	}

	// Replay from seq 3 onwards
	events = st.EventsSince(3, 50)
	if len(events) != 2 {
		t.Fatalf("EventsSince(3) = %d events, want 2", len(events))
	}
	if events[0].Seq != 4 {
		t.Errorf("first replayed seq = %d, want 4", events[0].Seq)
	}
}

func TestSequenceTracker_RingBufferOverflow(t *testing.T) {
	st := NewSequenceTracker(5) // small buffer

	// Record 8 events — should wrap around
	for i := 0; i < 8; i++ {
		st.RecordGuidance("space-1", "sess-1", 1, "")
	}

	if st.Count() != 5 {
		t.Errorf("count = %d, want 5 (buffer size)", st.Count())
	}

	// Only events 4-8 should be in buffer
	events := st.EventsSince(0, 50)
	if len(events) != 5 {
		t.Fatalf("EventsSince(0) = %d events, want 5", len(events))
	}
	if events[0].Seq != 4 {
		t.Errorf("oldest event seq = %d, want 4", events[0].Seq)
	}
	if events[4].Seq != 8 {
		t.Errorf("newest event seq = %d, want 8", events[4].Seq)
	}
}

func TestSequenceTracker_MaxEventsLimit(t *testing.T) {
	st := NewSequenceTracker(100)

	for i := 0; i < 20; i++ {
		st.RecordGuidance("space-1", "sess-1", 1, "")
	}

	// Request max 5 events
	events := st.EventsSince(0, 5)
	if len(events) != 5 {
		t.Fatalf("EventsSince with maxEvents=5 returned %d, want 5", len(events))
	}
}

func TestSequenceTracker_SetCounter(t *testing.T) {
	st := NewSequenceTracker(100)

	st.SetCounter(100)
	if st.Current() != 100 {
		t.Errorf("current after SetCounter(100) = %d, want 100", st.Current())
	}

	seq := st.Next()
	if seq != 101 {
		t.Errorf("Next() after SetCounter(100) = %d, want 101", seq)
	}
}

// defaultTestConfig returns a config suitable for testing escalation.
func defaultTestConfig() config.Config {
	return config.Config{
		JiminyEscalationEnabled:       true,
		JiminyEscalationWarnAfter:     2,
		JiminyEscalationEscalateAfter: 4,
		JiminyEscalationBlockAfter:    6,
		JiminyEscalationBlockEnabled:  true,
		JiminyEscalationDecayMinutes:  60,
	}
}
