package cli

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"mdemg/internal/sidecar"
)

func TestUninstallCmd_InvalidState(t *testing.T) {
	tests := []struct {
		name  string
		state sidecar.State
	}{
		{"uninitialized", sidecar.StateUninitialized},
		{"initialized", sidecar.StateInitialized},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			dir := t.TempDir()

			if tt.state == sidecar.StateInitialized {
				// Create a lock file with initialized state
				mdemgDir := filepath.Join(dir, ".mdemg")
				if err := os.MkdirAll(mdemgDir, 0755); err != nil {
					t.Fatalf("mkdir: %v", err)
				}
				lf := &sidecar.LockFile{
					State:     sidecar.StateInitialized,
					CreatedAt: sidecar.NowUTC(),
					UpdatedAt: sidecar.NowUTC(),
				}
				if err := sidecar.WriteLock(filepath.Join(mdemgDir, "sidecar.lock"), lf); err != nil {
					t.Fatalf("write lock: %v", err)
				}
			}

			origDir, _ := os.Getwd()
			if err := os.Chdir(dir); err != nil {
				t.Fatalf("chdir: %v", err)
			}
			defer func() { _ = os.Chdir(origDir) }()

			err := runSidecarUninstall(sidecarUninstallFlags{format: "text"})
			if err == nil {
				t.Fatal("expected error for invalid state, got nil")
			}
		})
	}
}

func TestUninstallCmd_RunningWithoutForce(t *testing.T) {
	dir := t.TempDir()
	mdemgDir := filepath.Join(dir, ".mdemg")
	if err := os.MkdirAll(mdemgDir, 0755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}

	lf := &sidecar.LockFile{
		State:     sidecar.StateRunning,
		CreatedAt: sidecar.NowUTC(),
		UpdatedAt: sidecar.NowUTC(),
	}
	if err := sidecar.WriteLock(filepath.Join(mdemgDir, "sidecar.lock"), lf); err != nil {
		t.Fatalf("write lock: %v", err)
	}

	origDir, _ := os.Getwd()
	if err := os.Chdir(dir); err != nil {
		t.Fatalf("chdir: %v", err)
	}
	defer func() { _ = os.Chdir(origDir) }()

	err := runSidecarUninstall(sidecarUninstallFlags{format: "text", force: false})
	if err == nil {
		t.Fatal("expected error for running state without force, got nil")
	}
	if !strings.Contains(err.Error(), "running") {
		t.Errorf("error = %q, want 'running' substring", err.Error())
	}
}

func TestUninstallCmd_RunningWithForce_Accepted(t *testing.T) {
	// Verify that --force with running state passes the state guard
	// (it will fail later due to no actual services, but won't reject the state)
	dir := t.TempDir()
	mdemgDir := filepath.Join(dir, ".mdemg")
	if err := os.MkdirAll(mdemgDir, 0755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}

	lf := &sidecar.LockFile{
		State:     sidecar.StateRunning,
		CreatedAt: sidecar.NowUTC(),
		UpdatedAt: sidecar.NowUTC(),
	}
	if err := sidecar.WriteLock(filepath.Join(mdemgDir, "sidecar.lock"), lf); err != nil {
		t.Fatalf("write lock: %v", err)
	}

	origDir, _ := os.Getwd()
	if err := os.Chdir(dir); err != nil {
		t.Fatalf("chdir: %v", err)
	}
	defer func() { _ = os.Chdir(origDir) }()

	// Force should pass the state guard (the down/detach calls may fail, but
	// the function should not return the "cannot uninstall while running" error)
	err := runSidecarUninstall(sidecarUninstallFlags{format: "text", force: true})
	if err != nil && strings.Contains(err.Error(), "cannot uninstall while sidecar is running") {
		t.Errorf("force flag should bypass running state guard, got: %v", err)
	}
	// err may be non-nil (down may fail without real services), that's OK
}

func TestUninstallReport_NilSliceSafety(t *testing.T) {
	report := sidecar.NewUninstallReport(
		sidecar.StateInstalled, sidecar.StateUninstalled, sidecar.ExitSuccess,
		false, false, "/backup/path",
	)

	data, err := json.Marshal(report)
	if err != nil {
		t.Fatalf("json.Marshal: %v", err)
	}

	var raw map[string]any
	if err := json.Unmarshal(data, &raw); err != nil {
		t.Fatalf("json.Unmarshal: %v", err)
	}

	for _, field := range []string{"changes", "issues", "next_actions"} {
		v, ok := raw[field]
		if !ok {
			t.Errorf("missing field %q in JSON", field)
			continue
		}
		arr, ok := v.([]any)
		if !ok {
			t.Errorf("field %q is not an array, got %T", field, v)
			continue
		}
		if len(arr) != 0 {
			t.Errorf("field %q should be empty, got %v", field, arr)
		}
	}
}

func TestIsSidecarGeneratedHook(t *testing.T) {
	dir := t.TempDir()

	// File with marker
	generated := filepath.Join(dir, "generated.sh")
	if err := os.WriteFile(generated, []byte("#!/bin/bash\n# Generated by: mdemg sidecar generate-hooks\necho ok\n"), 0755); err != nil {
		t.Fatalf("write: %v", err)
	}
	if !isSidecarGeneratedHook(generated) {
		t.Error("expected generated hook to be detected")
	}

	// File without marker
	manual := filepath.Join(dir, "manual.sh")
	if err := os.WriteFile(manual, []byte("#!/bin/bash\necho manual\n"), 0755); err != nil {
		t.Fatalf("write: %v", err)
	}
	if isSidecarGeneratedHook(manual) {
		t.Error("expected manual hook to not be detected as generated")
	}

	// Non-existent file
	if isSidecarGeneratedHook(filepath.Join(dir, "nope.sh")) {
		t.Error("expected non-existent file to return false")
	}
}
