"""Expert Selection Loader (Sprint FT-LORA-E Epic 2).

Parses Sprint D family profile artifacts (`profile_routing_{family}.json`)
and emits the module-path `keys` list that mlx_lm.tuner.utils.linear_to_lora_layers
consumes to train ONLY the top-25% routed experts per layer for Tier 2 LoRA.

The Sprint D artifact schema (generated by neural/training/profile_expert_routing.py):
    {
      "family": "reasoning_think" | "classify_notink" | "structured_notink",
      "model_sha256_config": "cdc167566e...",
      "num_layers": 40,
      "num_experts_per_layer": 256,
      "top_k_per_token": 8,
      "top_pct_selected": 25,
      "num_experts_selected_per_layer": 64,
      "per_layer": [
        {"layer": 0, "top_experts": [153, 42, ...], ...},
        ...
      ],
      ...
    }

The emitted `keys` target the Qwen3_5 MoE architecture expert module path:
    language_model.model.layers.{L}.mlp.experts.{E}.{down|up|gate}_proj

This string format was validated during Sprint D's monkey-patch of
Qwen3NextSparseMoeBlock (see profile_expert_routing.py). A Tier-2 integration
test cross-checks it against the real loaded model's named_parameters().
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Sequence


# Sprint D family names use underscores in the artifact files; CLI flags use
# hyphens (reasoning-think, classify-notink, structured-notink). This helper
# normalizes between the two canonical forms.
FAMILY_NAMES_UNDERSCORE = ("reasoning_think", "classify_notink", "structured_notink")
FAMILY_NAMES_HYPHEN = ("reasoning-think", "classify-notink", "structured-notink")


def normalize_family(name: str) -> str:
    """Normalize a family name to the underscore form used in artifact files.

    Accepts either the hyphen form (CLI flag) or the underscore form (file).
    """
    return name.replace("-", "_")


DEFAULT_PROJECTIONS: tuple[str, ...] = ("down", "up", "gate")
MODULE_PATH_TEMPLATE = "language_model.model.layers.{layer}.mlp.experts.{expert}.{proj}_proj"


@dataclass(frozen=True)
class ExpertSelection:
    """Loaded top-25% expert selection for one family, all layers."""

    family: str  # underscore form, e.g. "reasoning_think"
    top_experts_per_layer: list[list[int]]  # 40 × 64 ints
    num_layers: int
    num_experts_per_layer: int
    num_experts_selected_per_layer: int
    model_sha256_config: str

    @classmethod
    def load(cls, path: Path | str, expected_family: str) -> "ExpertSelection":
        """Load a Sprint D profile JSON and validate its schema + family.

        Args:
            path: path to profile_routing_{family}.json
            expected_family: family name (hyphen or underscore form accepted);
                normalized to underscore form for comparison with file.

        Raises:
            FileNotFoundError: artifact missing.
            ValueError: schema invalid, family mismatch, or layer count mismatch.
        """
        p = Path(path)
        if not p.exists():
            raise FileNotFoundError(f"Expert selection artifact not found: {p}")

        with p.open("r") as f:
            data = json.load(f)

        # Required schema fields (all present in Sprint D artifacts)
        required = {
            "family",
            "model_sha256_config",
            "num_layers",
            "num_experts_per_layer",
            "num_experts_selected_per_layer",
            "per_layer",
        }
        missing = required - set(data.keys())
        if missing:
            raise ValueError(
                f"Expert selection artifact {p} missing required fields: {sorted(missing)}"
            )

        file_family = data["family"]
        expected_norm = normalize_family(expected_family)
        if file_family != expected_norm:
            raise ValueError(
                f"Family mismatch in {p}: file says '{file_family}', "
                f"caller expected '{expected_norm}' (from --family={expected_family})"
            )

        num_layers = int(data["num_layers"])
        per_layer = data["per_layer"]
        if len(per_layer) != num_layers:
            raise ValueError(
                f"Layer count mismatch in {p}: num_layers={num_layers} "
                f"but len(per_layer)={len(per_layer)}"
            )

        num_selected = int(data["num_experts_selected_per_layer"])

        top_experts: list[list[int]] = []
        for idx, layer_entry in enumerate(per_layer):
            if "top_experts" not in layer_entry:
                raise ValueError(
                    f"{p}: per_layer[{idx}] missing 'top_experts'"
                )
            experts = [int(e) for e in layer_entry["top_experts"]]
            if len(experts) != num_selected:
                raise ValueError(
                    f"{p}: per_layer[{idx}].top_experts has {len(experts)} "
                    f"entries, expected {num_selected}"
                )
            top_experts.append(experts)

        return cls(
            family=file_family,
            top_experts_per_layer=top_experts,
            num_layers=num_layers,
            num_experts_per_layer=int(data["num_experts_per_layer"]),
            num_experts_selected_per_layer=num_selected,
            model_sha256_config=data["model_sha256_config"],
        )

    def mlx_lm_keys(
        self, projections: Sequence[str] = DEFAULT_PROJECTIONS
    ) -> list[str]:
        """Emit mlx_lm `keys` list for linear_to_lora_layers.

        For Sprint D artifacts (40 layers × 64 experts × 3 projections)
        this returns 7,680 module-path strings, e.g.
        'language_model.model.layers.0.mlp.experts.153.down_proj'.
        """
        keys: list[str] = []
        for layer_idx, experts in enumerate(self.top_experts_per_layer):
            for expert_idx in experts:
                for proj in projections:
                    keys.append(
                        MODULE_PATH_TEMPLATE.format(
                            layer=layer_idx, expert=expert_idx, proj=proj
                        )
                    )
        return keys

    def count(self, projections: Sequence[str] = DEFAULT_PROJECTIONS) -> int:
        return self.num_layers * self.num_experts_selected_per_layer * len(projections)
