apiVersion: v1
kind: Service
metadata:
  name: neural-sidecar
  labels:
    app.kubernetes.io/name: neural-sidecar
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: neural-sidecar
