apiVersion: 1
datasources:
  - name: Neo4j
    uid: neo4j
    type: kniepdennis-neo4j-datasource
    access: proxy
    editable: false
    jsonData:
      url: "bolt://host.docker.internal:7687"
      database: "neo4j"
      username: "neo4j"
    secureJsonData:
      password: "testpassword"
